# Generated by Django 5.1.3 on 2024-11-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('youtube_title', models.CharField(max_length=255)),
                ('blog_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['youtube_url'], name='api_blogpos_youtube_d35f65_idx'), models.Index(fields=['blog_title'], name='api_blogpos_blog_ti_1ba16c_idx'), models.Index(fields=['user'], name='api_blogpos_user_id_83ccd5_idx'), models.Index(fields=['author_name'], name='api_blogpos_author__194de5_idx')],
            },
        ),
    ]
