# Generated by Django 5.1.3 on 2024-11-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='management.invitecode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-banned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='management__code_db3da3_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['is_active'], name='management__is_acti_2ebba9_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecodeusage',
            index=models.Index(fields=['used_at'], name='management__used_at_86772c_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user'], name='management__user_id_29de43_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['banned_at'], name='management__banned__b6a330_idx'),
        ),
    ]
