# Generated by Django 5.1.3 on 2024-11-19 04:04

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=management.models.generate_invite_code, editable=False, max_length=8, unique=True),
        ),
    ]
